# Data Path https://data.caltech.edu/records/mzrjq-6wc02

#  Importing the required libraries

In [1]:
import tensorflow
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout,BatchNormalization
# from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping


# Initialising the CNN with 3 convolutional layers, filters, feature maps, fullyconnected layers,using drop out to prevent overfitting,padding,maxpooling


In [2]:
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32,kernel_size=(3, 3), padding='same',input_shape = (128, 128, 3), activation = 'relu'))
#classifier.add(BatchNormalization())

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
#classifier.add(BatchNormalization())

classifier.add(MaxPooling2D(pool_size = (2, 2)))

# # Adding a third convolutional layer

# classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
# #classifier.add(BatchNormalization())

# classifier.add(MaxPooling2D(pool_size = (2, 2)))

# # Adding a fourth convolutional layer


# classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
# #classifier.add(BatchNormalization())

# classifier.add(MaxPooling2D(pool_size = (2, 2)))



# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
Dropout(0.3)
# classifier.add(Dense(units = 64, activation = 'relu'))
# Dropout(0.3)
# classifier.add(Dense(units = 32, activation = 'relu'))
# Dropout(0.3)
classifier.add(Dense(8, activation = 'Softmax'))

# reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=np.sqrt(0.1), patience=5)


# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Importing ImageDataGenerator which helps us to normalize the data by bringing the data into range(0,1),setting batch size, target_size and requidred class_mode

In [3]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory(
    r'D:\QTInternship\caltech-101\caltech-101\traindata',
    target_size=(128, 128),
    batch_size=128,
    class_mode='categorical'  # For multiclass classification
)

test_set = test_datagen.flow_from_directory(
    r'D:\QTInternship\caltech-101\caltech-101\testdata',  # Ensure you have the correct path
    target_size=(128, 128),
    batch_size=128,
    class_mode='categorical'  # For multiclass classification
)

Found 970 images belonging to 8 classes.
Found 246 images belonging to 8 classes.


In [4]:
# reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=np.sqrt(0.1), patience=5)


# Fitting the model by specifying epochs

In [5]:
# Calculate steps per epoch
# steps_per_epoch = training_set.samples // training_set.batch_size
# print(steps_per_epoch)
# validation_steps = test_set.samples // test_set.batch_size
# print(validation_steps)


# Fit the model
classifier.fit(
    training_set,
#     steps_per_epoch=50,
    epochs=40,
    validation_data=test_set
#     validation_steps=50
)


Epoch 1/40
8/8 [==============================] - 10s 1s/step - loss: 1.7668 - accuracy: 0.5433 - val_loss: 1.2408 - val_accuracy: 0.6504
Epoch 2/40
8/8 [==============================] - 9s 1s/step - loss: 1.2106 - accuracy: 0.6691 - val_loss: 1.0883 - val_accuracy: 0.6829
Epoch 3/40
8/8 [==============================] - 9s 1s/step - loss: 1.0612 - accuracy: 0.6887 - val_loss: 0.9945 - val_accuracy: 0.6992
Epoch 4/40
8/8 [==============================] - 9s 1s/step - loss: 0.9503 - accuracy: 0.7031 - val_loss: 0.8289 - val_accuracy: 0.7073
Epoch 5/40
8/8 [==============================] - 8s 1s/step - loss: 0.8208 - accuracy: 0.7402 - val_loss: 0.7411 - val_accuracy: 0.7439
Epoch 6/40
8/8 [==============================] - 11s 1s/step - loss: 0.7204 - accuracy: 0.7649 - val_loss: 0.6324 - val_accuracy: 0.7724
Epoch 7/40
8/8 [==============================] - 11s 1s/step - loss: 0.6400 - accuracy: 0.7804 - val_loss: 0.6162 - val_accuracy: 0.7724
Epoch 8/40
8/8 [======================

# Testing our models performance by selecting specific images

In [7]:
import numpy as np
from tensorflow.keras.preprocessing import image

#from keras.preprocessing import image
test_image = image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/airplane.jpeg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 64ms/step


In [8]:
print(result)

[[1. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/butterfly.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 37ms/step


In [10]:
print(result)

[[0. 1. 0. 0. 0. 0. 0. 0.]]


In [13]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/cougar_body1.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 31ms/step


In [14]:
print(result)

[[0. 0. 1. 0. 0. 0. 0. 0.]]


In [15]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/cougar_face.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 27ms/step


In [16]:
print(result)

[[0. 0. 0. 1. 0. 0. 0. 0.]]


In [21]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/Saltwater_crocodile.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 16ms/step


In [22]:
print(result)

[[0. 0. 0. 0. 1. 0. 0. 0.]]


In [31]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/Crocodilehead.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 16ms/step


In [32]:
print(result)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  3.6971433e-29 0.0000000e+00 1.0000000e+00]]


In [34]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/dragonfly.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 31ms/step


In [35]:
print(result)

[[0. 0. 0. 0. 0. 0. 1. 0.]]


In [40]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/testcheckimages/mayfly2.jpg'
                   , target_size=(128, 128))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 24ms/step


In [41]:
print(result)

[[0. 0. 0. 0. 0. 0. 0. 1.]]


# Data Labels used for ImageClassification

## airplanes
## butterfly
## cougar_body
## cougar_face
## crocodile
## crocodile_head
## dragonfly
## mayfly
