# Data Path https://data.caltech.edu/records/mzrjq-6wc02

#  Importing the required libraries

In [1]:
import tensorflow
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout,BatchNormalization
# from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping


# Initialising the CNN with 3 convolutional layers, filters, feature maps, fullyconnected layers,using drop out to prevent overfitting,padding,maxpooling


In [4]:
classifier = Sequential()

# Step 1 - Convolution
classifier.add(Conv2D(32,kernel_size=(3, 3), padding='same',input_shape = (300, 300, 3), activation = 'relu'))
#classifier.add(BatchNormalization())

# Step 2 - Pooling
classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a second convolutional layer
classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
#classifier.add(BatchNormalization())

classifier.add(MaxPooling2D(pool_size = (2, 2)))

# Adding a third convolutional layer

classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
#classifier.add(BatchNormalization())

classifier.add(MaxPooling2D(pool_size = (2, 2)))

# # Adding a fourth convolutional layer


# classifier.add(Conv2D(32,kernel_size=(3, 3),padding='same', activation = 'relu'))
# #classifier.add(BatchNormalization())

# classifier.add(MaxPooling2D(pool_size = (2, 2)))



# Step 3 - Flattening
classifier.add(Flatten())

# Step 4 - Full connection
classifier.add(Dense(units = 128, activation = 'relu'))
Dropout(0.5)
classifier.add(Dense(units = 64, activation = 'relu'))
Dropout(0.5)
classifier.add(Dense(units = 32, activation = 'relu'))
Dropout(0.5)
classifier.add(Dense(5, activation = 'Softmax'))

# reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=np.sqrt(0.1), patience=5)


# Compiling the CNN
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# Importing ImageDataGenerator which helps us to normalize the data by bringing the data into range(0,1),setting batch size, target_size and requidred class_mode

In [5]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

training_set = train_datagen.flow_from_directory(
    r'D:\QTInternship\caltech-101\caltech-101\training_data_multiclass_6',
    target_size=(300, 300),
    batch_size=100,
    class_mode='categorical'  # For multiclass classification
)

test_set = test_datagen.flow_from_directory(
    r'D:\QTInternship\caltech-101\caltech-101\testing_data_multiclass_6',  # Ensure you have the correct path
    target_size=(300, 300),
    batch_size=100,
    class_mode='categorical'  # For multiclass classification
)

Found 96 images belonging to 5 classes.
Found 98 images belonging to 5 classes.


In [6]:
# reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=np.sqrt(0.1), patience=5)


# Fitting the model by specifying epochs

In [7]:
# Calculate steps per epoch
# steps_per_epoch = training_set.samples // training_set.batch_size
# print(steps_per_epoch)
# validation_steps = test_set.samples // test_set.batch_size
# print(validation_steps)


# Fit the model
classifier.fit(
    training_set,
#     steps_per_epoch=50,
    epochs=50,
    validation_data=test_set
#     validation_steps=50
)


Epoch 1/50
1/1 [==============================] - 7s 7s/step - loss: 1.6096 - accuracy: 0.2500 - val_loss: 4.7813 - val_accuracy: 0.3265
Epoch 2/50
1/1 [==============================] - 6s 6s/step - loss: 4.2667 - accuracy: 0.2708 - val_loss: 1.8387 - val_accuracy: 0.2041
Epoch 3/50
1/1 [==============================] - 6s 6s/step - loss: 1.7457 - accuracy: 0.2708 - val_loss: 1.5851 - val_accuracy: 0.2245
Epoch 4/50
1/1 [==============================] - 6s 6s/step - loss: 1.5237 - accuracy: 0.3333 - val_loss: 1.5624 - val_accuracy: 0.2755
Epoch 5/50
1/1 [==============================] - 6s 6s/step - loss: 1.4959 - accuracy: 0.4479 - val_loss: 1.5180 - val_accuracy: 0.3776
Epoch 6/50
1/1 [==============================] - 6s 6s/step - loss: 1.4132 - accuracy: 0.5521 - val_loss: 1.5224 - val_accuracy: 0.3878
Epoch 7/50
1/1 [==============================] - 6s 6s/step - loss: 1.3492 - accuracy: 0.5208 - val_loss: 1.5301 - val_accuracy: 0.3673
Epoch 8/50
1/1 [=========================

# Testing our models performance by selecting specific images

In [8]:
import numpy as np
from tensorflow.keras.preprocessing import image

#from keras.preprocessing import image
test_image = image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/airplanes/image_0164.jpg'
                   , target_size=(300, 300))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 191ms/step


In [9]:
print(result)

[[1. 0. 0. 0. 0.]]


In [10]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/butterfly/image_0016.jpg'
                   , target_size=(300, 300))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 63ms/step


In [11]:
print(result)

[[0. 1. 0. 0. 0.]]


In [12]:
# import numpy as np
# from tensorflow.keras.preprocessing import image

# test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/dragonfly/image_0026.jpg'
#                    , target_size=(300, 300))
# test_image = image.img_to_array(test_image)
# test_image = np.expand_dims(test_image, axis=0)
# result = classifier.predict(test_image)

In [14]:
# import numpy as np
# from tensorflow.keras.preprocessing import image

# test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/dragonfly/image_0030.jpg'
#                    , target_size=(300, 300))
# test_image = image.img_to_array(test_image)
# test_image = np.expand_dims(test_image, axis=0)
# result = classifier.predict(test_image)

In [26]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/car_side/image_0045.jpg'
                   , target_size=(300, 300))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 32ms/step


In [27]:
print(result)

[[0.00000e+00 2.40614e-10 1.00000e+00 0.00000e+00 0.00000e+00]]


In [18]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/cellphone/image_0034.jpg'
                   , target_size=(300, 300))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 41ms/step


In [19]:
print(result)

[[0. 0. 0. 1. 0.]]


In [24]:
import numpy as np
from tensorflow.keras.preprocessing import image

test_image =image.load_img('D:/QTInternship/caltech-101/caltech-101/101_ObjectCategories/cougar_body/image_0029.jpg'
                   , target_size=(300, 300))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis=0)
result = classifier.predict(test_image)

1/1 [==============================] - 0s 41ms/step


In [25]:
print(result)

[[0. 0. 0. 0. 1.]]


# Data Labels used for ImageClassification

## airplanes
## butterfly
## car_side
## cellphone
## cougar_body
